import hashlib
from dataclasses import dataclass, field
from typing import List

# Write test file
lines = []
lines.append("class TestTranscriptLanguage:")
lines.append("    def test_spanish_value(self):")
lines.append("        assert TranscriptLanguage.SPANISH.value == \"Spanish\"")
lines.append("")
lines.append("    def test_catalan_value(self):")
lines.append("        assert TranscriptLanguage.CATALAN.value == \"Catalan\"")
lines.append("")
lines.append("    def test_chinese_value(self):")
lines.append("        assert TranscriptLanguage.CHINESE.value == \"Chinese\"")
lines.append("")
lines.append("    def test_english_value(self):")
lines.append("        assert TranscriptLanguage.ENGLISH.value == \"English\"")
lines.append("")
lines.append("    def test_unknown_value(self):")
lines.append("        assert TranscriptLanguage.UNKNOWN.value == \"Unknown\"")
lines.append("")
lines.append("    def test_from_string_spanish(self):")
lines.append("        assert TranscriptLanguage.from_string(\"spanish\") == TranscriptLanguage.SPANISH")
lines.append("")
lines.append("    def test_from_string_catalan(self):")
lines.append("        assert TranscriptLanguage.from_string(\"catalan\") == TranscriptLanguage.CATALAN")
lines.append("")
lines.append("    def test_from_string_unknown(self):")
lines.append("        assert TranscriptLanguage.from_string(\"french\") == TranscriptLanguage.UNKNOWN")
lines.append("")
lines.append("class TestTranscriptSegment:")
lines.append("    def test_default_values(self):")
lines.append("        seg = TranscriptSegment()")
lines.append("        assert seg.start == 0.0")
lines.append("        assert seg.end == 0.0")
lines.append("        assert seg.text == \"\"")
lines.append("        assert seg.speaker == \"\"")
lines.append("        assert seg.language == TranscriptLanguage.UNKNOWN")
lines.append("        assert seg.confidence == 0.0")
lines.append("")
lines.append("    def test_custom_values(self):")
lines.append("        seg = TranscriptSegment(start=1.0, end=3.5, text=\"Hello\", speaker=\"Teacher\", language=TranscriptLanguage.SPANISH, confidence=0.95)")
lines.append("        assert seg.start == 1.0")
lines.append("        assert seg.end == 3.5")
lines.append("        assert seg.text == \"Hello\"")
lines.append("        assert seg.speaker == \"Teacher\"")
lines.append("        assert seg.language == TranscriptLanguage.SPANISH")
lines.append("        assert seg.confidence == 0.95")
lines.append("")
lines.append("    def test_negative_start_clamped(self):")
lines.append("        seg = TranscriptSegment(start=-1.0, end=2.0, text=\"Test\")")
lines.append("        assert seg.start == 0.0")
lines.append("")
lines.append("    def test_end_less_than_start(self):")
lines.append("        seg = TranscriptSegment(start=5.0, end=2.0, text=\"Test\")")
lines.append("        assert seg.end == 5.0")
lines.append("")
lines.append("    def test_empty_text(self):")
lines.append("        seg = TranscriptSegment(start=0.0, end=1.0, text=\"   \")")
lines.append("        assert seg.text == \"\"")
lines.append("")
lines.append("    def test_to_dict(self):")
lines.append("        seg = TranscriptSegment(start=0.0, end=1.5, text=\"Hola\", speaker=\"Teacher\", language=TranscriptLanguage.SPANISH, confidence=0.9)")
lines.append("        d = seg.to_dict()")
lines.append("        assert d[\"start\"] == 0.0")
lines.append("        assert d[\"end\"] == 1.5")
lines.append("        assert d[\"text\"] == \"Hola\"")
lines.append("        assert d[\"language\"] == \"Spanish\"")
lines.append("        assert d[\"confidence\"] == 0.9")
lines.append("")
lines.append("    def test_from_dict(self):")
lines.append("        data = {\"start\": 1.0, \"end\": 2.0, \"text\": \"Hello\", \"speaker\": \"Student\", \"language\": \"Spanish\", \"confidence\": 0.8}")
lines.append("        seg = TranscriptSegment.from_dict(data)")
lines.append("        assert seg.start == 1.0")
lines.append("        assert seg.text == \"Hello\"")
lines.append("        assert seg.language == TranscriptLanguage.SPANISH")
lines.append("")
lines.append("    def test_from_dict_with_unknown_language(self):")
lines.append("        data = {\"start\": 0.0, \"end\": 1.0, \"text\": \"Test\"}")
lines.append("        seg = TranscriptSegment.from_dict(data)")
lines.append("        assert seg.language == TranscriptLanguage.UNKNOWN")
lines.append("")

with open(r"D:\Project\Clases\tests\test_transcription.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("Part 1 written")
